[project]
name = "football-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dvc>=3.66.1",
    "ipykernel>=7.1.0",
    "roboflow>=1.2.11",
    "ultralytics>=8.3.252",
]
